"""empty message

Revision ID: 764726025264
Revises: 464ee060d58b
Create Date: 2019-11-06 09:20:45.454469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764726025264'
down_revision = '464ee060d58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meso_name', table_name='meso')
    op.create_index(op.f('ix_meso_name'), 'meso', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meso_name'), table_name='meso')
    op.create_index('ix_meso_name', 'meso', ['name'], unique=1)
    # ### end Alembic commands ###
